"""init

Revision ID: 2847c77b3d6b
Revises:
Create Date: 2025-12-26 14:48:52.784482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2847c77b3d6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bank', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('raw_json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('balance_date', sa.DateTime(), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('raw_json', sa.String(), nullable=False),
    sa.Column('payee', sa.String(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('transacted_at', sa.DateTime(), nullable=False),
    sa.Column('extra_attrs', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('balance')
    op.drop_table('account')
    # ### end Alembic commands ###
