"""add balance raw json

Revision ID: 7654534a85bd
Revises: b40ca8183247
Create Date: 2025-12-26 15:34:02.579623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7654534a85bd'
down_revision: Union[str, Sequence[str], None] = 'b40ca8183247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('raw_json', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance', 'raw_json')
    # ### end Alembic commands ###
