"""add querylog

Revision ID: b40ca8183247
Revises: 2847c77b3d6b
Create Date: 2025-12-26 15:24:00.147508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40ca8183247'
down_revision: Union[str, Sequence[str], None] = '2847c77b3d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_date', sa.DateTime(), nullable=False),
    sa.Column('days_history', sa.Integer(), nullable=False),
    sa.Column('raw_response', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_log')
    # ### end Alembic commands ###
